/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import bo.UsuarioBO;
import ctrl.UsuarioCTRL;
import javax.swing.JOptionPane;

/**
 *
 * @author Gui Freitas
 */
public class ManterUsuario extends javax.swing.JInternalFrame {

    UsuarioBO usuarioBo = new UsuarioBO();
    UsuarioCTRL usuarioCtrl = new UsuarioCTRL();
    String op = "";

    /**
     * Creates new form ManterUsuario
     */
    public ManterUsuario() {
        initComponents();
        DesabilitaCampos();
    }

    private void DesabilitaCampos() {
        txt_cpf.setEditable(false);
        cb_ativo.setEnabled(false);
        txt_nome.setEditable(false);
        txt_senha.setEditable(false);
        txt_senha1.setEditable(false);
        cmb_acesso.setEditable(false);
        bt_salvar.setEnabled(false);
        bt_editar.setEnabled(false);
    }

    private void HabilitaCampos() {
        txt_cpf.setEditable(true);
        cb_ativo.setEnabled(true);
        txt_nome.setEditable(true);
        txt_senha.setEditable(true);
        txt_senha1.setEditable(true);
        cmb_acesso.setEditable(true);
        bt_salvar.setEnabled(true);
        bt_editar.setEnabled(true);
    }

    private void LimparCampos() {
        txt_matricula.setText(null);
        txt_cpf.setText(null);
        cb_ativo.setSelected(false);
        txt_nome.setText(null);
        txt_senha.setText(null);
        txt_senha1.setText(null);
        cmb_acesso.setSelectedItem("Secretária");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_salvar = new javax.swing.JButton();
        bt_fechar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb_ativo = new javax.swing.JCheckBox();
        txt_cpf = new javax.swing.JFormattedTextField();
        txt_senha = new javax.swing.JPasswordField();
        cmb_acesso = new javax.swing.JComboBox();
        txt_senha1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JFormattedTextField();
        txt_nome = new javax.swing.JFormattedTextField();
        bt_novo = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();

        setTitle("Cadastro de Usuários");

        bt_salvar.setText("Salvar");
        bt_salvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_salvar.setVerifyInputWhenFocusTarget(false);
        bt_salvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_fechar.setText("Fechar");
        bt_fechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_fechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fecharActionPerformed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));
        jLayeredPane1.setToolTipText("");

        jLabel1.setText("Matrícula :");

        jLabel3.setText("Nome :");

        jLabel4.setText("CPF:");

        jLabel5.setText("Acesso :");

        jLabel6.setText("Senha :");

        cb_ativo.setText("Ativo");
        cb_ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ativoActionPerformed(evt);
            }
        });

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.setToolTipText("");
        txt_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpfActionPerformed(evt);
            }
        });
        txt_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cpfFocusLost(evt);
            }
        });

        cmb_acesso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Secretária", "Gerente" }));
        cmb_acesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_acessoActionPerformed(evt);
            }
        });

        jLabel7.setText("Confirme a senha :");

        try {
            txt_matricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_nome.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("****************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cb_ativo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txt_cpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txt_senha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmb_acesso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txt_senha1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txt_matricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txt_nome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_ativo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmb_acesso, javax.swing.GroupLayout.Alignment.LEADING, 0, 92, Short.MAX_VALUE)
                            .addComponent(txt_senha, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_senha1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_nome))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_ativo)
                    .addComponent(jLabel4)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txt_senha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_novo.setText("Novo");
        bt_novo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_novo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        bt_editar.setText("Editar");
        bt_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_buscar.setText("Buscar");
        bt_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_fechar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_novo)
                    .addComponent(bt_salvar)
                    .addComponent(bt_fechar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_editar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_ativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_ativoActionPerformed

    private void bt_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_fecharActionPerformed

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        HabilitaCampos();
        op = "incluir";
    }//GEN-LAST:event_bt_novoActionPerformed

    private void txt_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpfActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        int valida = 0;

        if ((txt_matricula == null) || (txt_cpf == null) || (txt_nome == null)) {
            JOptionPane.showMessageDialog(null, "Informe todos os dados antes de salvar.");
            valida = 1;
        }

        while (valida == 0) {
            Boolean validaSenha = ValidaSenha();
            if (validaSenha = true) {
                try {
                    usuarioBo.setMatricula(Integer.parseInt(txt_matricula.getText()));
                    usuarioBo.setStatus(cb_ativo.isSelected());
                    usuarioBo.setCpf(txt_cpf.getText());
                    usuarioBo.setNome(txt_nome.getText());
                    usuarioBo.setSenha(txt_senha.getText());
                    usuarioBo.setAcesso(cmb_acesso.getSelectedIndex());

                    if ("incluir".equals(op)) {
                        usuarioCtrl.IncluirUsuario(usuarioBo);
                    }

                    if ("alterar".equals(op)) {
                        usuarioCtrl.AlterarUsuario(usuarioBo);
                    }

                    JOptionPane.showMessageDialog(null, "Salvo com sucesso.");
                    LimparCampos();
                    DesabilitaCampos();
                    bt_novo.setEnabled(true);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Senha incorreta. Verifique a senha informada.");
                txt_senha.setText(null);
                txt_senha1.setText(null);
            }
            op = "";
            valida = 1;
        }
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        UsuarioBO retorno = new UsuarioBO();
        try {
            usuarioBo.setMatricula(Integer.parseInt(txt_matricula.getText()));
            retorno = usuarioCtrl.BuscaMatricula(usuarioBo);

            txt_matricula.setText(String.valueOf(retorno.getMatricula()));
            cb_ativo.setSelected(retorno.getStatus());
            txt_cpf.setText(retorno.getCpf());
            txt_nome.setText(retorno.getNome());
            txt_senha.setText(retorno.getSenha());
            txt_senha1.setText(retorno.getSenha());
            cmb_acesso.setSelectedIndex(retorno.getAcesso());
            bt_editar.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Matricula não encontrada.");
        }
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        op = "alterar";
        bt_salvar.setEnabled(true);
        bt_novo.setEnabled(false);
        HabilitaCampos();

    }//GEN-LAST:event_bt_editarActionPerformed

    private void txt_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpfFocusLost

        boolean retorno;
        retorno = ctrl.ValidadoresCTRL.validaCpf(txt_cpf.getText());
        if (retorno == false) {
            JOptionPane.showMessageDialog(null, "CPF inválido!");
            txt_cpf.setText("");
            txt_cpf.requestFocus();
        }

    }//GEN-LAST:event_txt_cpfFocusLost

    private void cmb_acessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_acessoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_acessoActionPerformed

    public Boolean ValidaSenha() {
        Boolean retorno = false;
        if (txt_senha.getText().equals(txt_senha1.getText())) {
            retorno = true;
        }
        return retorno;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_fechar;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JCheckBox cb_ativo;
    private javax.swing.JComboBox cmb_acesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JFormattedTextField txt_matricula;
    private javax.swing.JFormattedTextField txt_nome;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JPasswordField txt_senha1;
    // End of variables declaration//GEN-END:variables
}
